version: 0.2
env:
  variables:
    INDY_ENV: test
  exported-variables:
      - IndexName
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - export FOO=bar
      - export BAR=baz
  post_build:
    commands:
      - export IndexName=index.$(date +%Y-%m-%d-%H-%M-%S).html
      - cd dist && cp index.html $IndexName
      - echo post build ran at `date`
artifacts:
  base-directory: 'dist'
  files:
    - '**/*'
