version: 0.2
env:
  variables:
    INDY_ENV: test
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo post build ran at `date`
artifacts:
  files:
    - '**/*'
